version: 2
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run test
  deploy:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release
          command: npm run semantic-release || true
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
